# partly from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Create and publish a Docker image

permissions: write-all
on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
  REGISTRY: 007640530078.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_NAME: ${{ github.repository }}  # The owner and repository name. For example, caseware/imagepullsecret-patcher

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: extract_branch

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: (UST1) Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        id: configure-aws-credentials
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TEST }}
          role-session-name: publish-imagepullsecret-patcher
          aws-region: us-east-1

      - name: AWS ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: '${{ steps.configure-aws-credentials.outputs.aws-account-id }}'

      - name: Build and push to Docker registry
        run: |
          docker build . -t "$IMAGE_NAME"
          docker tag "$IMAGE_NAME" "${REGISTRY}/${IMAGE_NAME}:${VERSION}"
          docker push "${REGISTRY}/${IMAGE_NAME}:${VERSION}"
        env:
          VERSION: ${{ steps.extract_branch.outputs.branch }}-sha-${{ steps.extract_branch.outputs.short_sha }}-run-${{ github.run_number }}
